name: auth_boilerplate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: ^1.15.0
  hooks_riverpod: ^2.5.4
  flutter_hooks: ^0.20.5
  form_builder_validators: ^11.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  go_router: ^14.3.0
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.8
  mockito: ^5.4.4
  build_runner: ^2.4.13
  firebase_auth_mocks: ^0.14.1

flutter:
  uses-material-design: true

